// Code generated by "stringer -type ProtocolType"; DO NOT EDIT.

package main

import "fmt"

const _DeviceType_name = "UnknownGTWT01"

var _DeviceType_index = [...]uint8{0, 7, 15}

func (i ProtocolType) String() string {
	if i >= ProtocolType(len(_DeviceType_index)-1) {
		return fmt.Sprintf("ProtocolType(%d)", i)
	}
	return _DeviceType_name[_DeviceType_index[i]:_DeviceType_index[i+1]]
}
