// Code generated by "stringer -type DeviceType"; DO NOT EDIT.

package main

import "fmt"

const _DeviceType_name = "UnknownGT_WT_01"

var _DeviceType_index = [...]uint8{0, 7, 15}

func (i DeviceType) String() string {
	if i >= DeviceType(len(_DeviceType_index)-1) {
		return fmt.Sprintf("DeviceType(%d)", i)
	}
	return _DeviceType_name[_DeviceType_index[i]:_DeviceType_index[i+1]]
}
